[pytest]
log_cli = true
log_cli_format = %(levelname)s %(asctime)s %(message)s
asyncio_mode = auto
addopts = -p no:warnings --color=yes
norecursedirs = .git .github .pytest_cache .ruff_cache .venv

[pytest_env]
DB_NAME = test_demetra
