mutation UpdateIssue($issueId: String!, $stateId: String!) {
  issueUpdate(input: {id: $issueId, stateId: $stateId}) {
    success
    issue {
      id
      state {
        id
        name
      }
    }
  }
}