query GetIssueById($issueId: String!) {
  issue(id: $issueId) {
    id
    identifier
    state {
      id
      name
    }
    title
    description
    priority
    createdAt
    branchName
    project {
      id
      name
    }
      labels {
        nodes {
          id
          name
        }
      }
      comments(first: 100, filter: {parent: {null: true}}) {
      nodes {
        body
        resolvedAt
        createdAt
        user {
          name
        }
        children {
          edges {
            node {
              id
              body
              createdAt
              user {
                name
              }
            }
          }
        }
      }
    }
  }
}
