query GetIssues($state_id: String!) {
  issues(first: 100, filter: {state: {name: {eq: $state_id}}}) {
    nodes {
      id
      identifier
      state {
        id
        name
      }
      title
      description
      priority
      createdAt
      branchName
      project {
        id
        name
      }
      comments(first: 100, filter: {parent: {null: true}}) {
        nodes {
          body
          resolvedAt
          createdAt
          user {
            name
          }
          children {
            edges {
              node {
                id
                body
                createdAt
                user {
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
