query GetIssues {
  issues(first: 100) {
    nodes {
      id
      identifier
      state {
        id
        name
      }
      title
      description
      priority
      createdAt
      branchName
      project {
        id
        name
      }
      comments(first: 10) {
        nodes {
          body
        }
      }
    }
  }
}
